server:
  port: 3344
spring:
  application:
    name:  springcloud-config-server  #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/weixiaohuai/spring-cloud-config.git #Gitee上面的git仓库名字
          #Gitee仓库中配置文件所在的目录
          search-paths:
            - spring-cloud-config
          #访问git仓库的用户名(如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写)
#          username:
          #访问git仓库的密码
#          password:
      #读取的分支名称
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://springcloud-eureka7001.com:7001/eureka/,http://springcloud-eureka7002.com:7002/eureka/   #集群版Eureka注册中心


