server:
  port: 8801
spring:
  application:
    name: springcloud-stream-rabbitmq-provider
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息
        rabbitmq_binder: # binder绑定器名称，用于binding整合
          type: rabbit # 消息组件类型 如果消息中间件是kafka,则type:kafka
          environment: # rabbitmq相关环境配置
            spring:
              rabbitmq:
                host: localhost  #rabbitmq主机
                port: 5672 #rabbitmq端口
                username: guest #rabbitmq用户名
                password: guest #rabbitmq用户密码
      bindings: # 服务的整合处理
        output: # 输出通道,表示消息生产方
          destination: rabbitmq_stream_exchange   # 指定输出的交换器名称
          content-type: application/json  # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: rabbitmq_binder   # 指定binder的名称,需与上面spring.cloud.stream.binders.xxx中的xxx绑定器名称对应
eureka:
  client:
    service-url:
      defaultZone: http://springcloud-eureka7001.com:7001/eureka/,http://springcloud-eureka7002.com:7002/eureka/   #集群版Eureka注册中心






