server:
  port: 8002    #指定服务端口号
spring:
  application:
    name: springcloud-payment-service  #指定服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver             # mysql驱动包&useSSL=false
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8  #数据库地址
    username: root  #数据库用户名
    password: root  #数据库用户密码
mybatis:
  mapperLocations: classpath:mapper/*.xml   #mapper.xml文件扫描位置
  type-aliases-package: com.wsh.springcloud.entity    # 所有Entity别名类所在包
eureka:
  client:
    register-with-eureka: true  #注册到Eureka注册中心
    fetch-registry: true  #开启检索服务
    service-url:
#      defaultZone: http://localhost:7001/eureka/    #单机版Eureka注册中心
      defaultZone: http://springcloud-eureka7001.com:7001/eureka/,http://springcloud-eureka7002.com:7002/eureka/   #集群版Eureka注册中心
