server:
  port: 8804
spring:
  application:
    name: springcloud-stream-rabbitmq-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        customInput:
          destination: rabbitmq-stream-topic  #指定输入通道对应的主题名
        customOutput:
          destination: rabbitmq-stream-topic  #指定输出通道对应的主题名
eureka:
  client:
    service-url:
      defaultZone: http://springcloud-eureka7001.com:7001/eureka/,http://springcloud-eureka7002.com:7002/eureka/   #集群版Eureka注册中心










