server:
  port: 2002

spring:
  application:
    name: springcloudalibaba-seata-storage-service
  cloud:
    alibaba:
      seata:
        tx-service-group: wsh_tx_group   #自定义事务组名称，需要与file.conf中配置的名称对应(vgroup_mapping.my_test_tx_group = "wsh_tx_group")
    nacos:
      discovery:
        server-addr: localhost:8848  #指定nacos注册地址
  datasource:   #mysql数据源连接配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage
    username: root
    password: 514730
    hikari:
      connection-timeout: 50000
      druid:
        max-wait: 50000
logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml   #指定mybatis mapper文件地址


