server:
  port: 84
spring:
  application:
    name: springcloudalibaba-consumer-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #配置nacos服务器地址
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
feign:
  sentinel:
    enabled: true  # 激活Sentinel对Feign的支持
#设置feign客户端超时时间(OpenFeign默认支持ribbon)  OpenFeign客户端一般默认等待1秒钟
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    #以debug日志级别监控PaymentServiceFeignClient这个接口
    com.wsh.springcloud.alibaba.feign.PaymentFeignClient: debug