server:
  port: 7002
spring:
  application:
    name: springcloud-eureka-server  #应用名称
eureka:
  instance:
    hostname: springcloud-eureka7002.com  #eureka服务端的实例名称
  client:
    fetch-registry: true    #false表示不需要去检索服务实例
    register-with-eureka: true   #false表示不向注册中心注册自己
    service-url:
      defaultZone: http://springcloud-eureka7001.com:7001/eureka/