server:
  port: 2003
spring:
  application:
    name: springcloudalibaba-seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: wsh_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account
    username: root
    password: 514730
    hikari:
      connection-timeout: 50000
    druid:
      max-wait: 50000
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml


