server:
  port: 9003
spring:
  application:
    name: springcloudalibaba-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露端点配置





