server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://springcloud-eureka7001.com:7001/eureka/,http://springcloud-eureka7002.com:7002/eureka/   #集群版Eureka注册中心
feign:
  hystrix:
    enabled: true