server:
  port: 8401
spring:
  application:
    name: springcloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #指定nacos服务器地址
    sentinel:
      transport:
        dashboard: localhost:8080   #指定sentinel控制台的地址t
        port: 8719  #sentinel api端口, 默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
management:
  endpoints:
    web:
      exposure:
        include: '*'   #配置对外暴露端口