server:
  port: 9527
spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
        #如下配置表示,当浏览器URL访问localhost:9527/gatewaySimple/**的时候,gateway网关会帮忙转发到http://localhost:8001/gatewaySimple/**去.
        - id: payment8001_gatewaySimple  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001   #指定payment8001的访问地址,即匹配后提供服务的路由地址
          predicates:
            - Path=/gatewaySimple/**         # 断言，路径相匹配的进行路由

        #如下配置表示,当浏览器URL访问localhost:9527/gatewayLoadBalance/**的时候,gateway网关负载均衡地将请求分发到springcloud-payment-service服务中去.
        - id: payment_service_loadbalance  #路由ID
          uri: lb://springcloud-payment-service  #springcloud-payment-service为服务提供者注册到Eureka的应用名称(application name)
          predicates:
            - Path=/gatewayLoadBalance/**         # 断言，路径相匹配的进行路由
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
eureka:
  instance:
    hostname: springcloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://springcloud-eureka7001.com:7001/eureka/,http://springcloud-eureka7002.com:7002/eureka/   #集群版Eureka注册中心


