server:
  port: 7001
spring:
  application:
    name: springcloud-eureka-server  #应用名称
eureka:
  instance:
    hostname: springcloud-eureka7001.com  #eureka服务端的实例名称
  client:
    fetch-registry: true    #false表示不需要去检索服务实例
    register-with-eureka: true   #false表示不向注册中心注册自己
    service-url:
      defaultZone: http://springcloud-eureka7002.com:7002/eureka/
  server:
    enable-self-preservation: true  #默认开启自我保护,false表示关闭自我保护模式,及时剔除不可用的服务实例
#    eviction-interval-timer-in-ms: 2000